name = "DeepcopyModules"
uuid = "6f12c252-8bf0-11e9-1bb6-ff8912d7735c"
authors = ["Nathan Daly <nhdaly@gmail.com>"]
version = "0.2.0"

[compat]
julia = "1.1"

[deps]

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "Test"]
